language: php
php:
    - 5.4
before_install:
install:
before_script:
    -composer install --dev --prefer-source
    - chmod +x /
#script: vendor/bin/phpunit
script: bin/behat Tests/Goutte/test.feature
email:
    recipients:
      - anthonydeniaud@gmail.com
    #on_success: always #doc: http://about.travis-ci.org/docs/user/notifications/
