language: php
php:
    - 5.4
before_install:
        - sudo apt-get update
        - sudo apt-get install apache2
#        - composer install --dev --prefer-source
#        - chmod +x bin/behat
        - sudo chmod 777 /var/www
        - cd /var/www
        - sudo mkdir test
        - cd test
install:
before_script:
#script: vendor/bin/phpunit
script: bin/behat Tests/Goutte/test.feature
email:
    recipients:
      - anthonydeniaud@gmail.com
    #on_success: always #doc: http://about.travis-ci.org/docs/user/notifications/
