language: php
php:
    - 5.4
before_install:
        - sudo apt-get update
        - download sahi_installer jar
        - open a console
        - open java -jar path/to/sahi_installer
#
        - sudo apt-get install apache2
        - sudo apt-get install libapache2-mod-php5
        - sudo apt-get install firefox
#        - firefox -v
#        - composer install --dev --prefer-source
        - chmod +x bin/behat
        - sudo chmod 777 /var/www
        - cp -r /home/travis/build/TWAD/tests /var/www/TEST
        - cd /var/www/TEST
        - sh -e /etc/init.d/xvfb start
        - export DISPLAY=:99.0
#        - wget https://selenium.googlecode.com/files/selenium-server-standalone-2.35.0.jar
#        - java -jar "selenium-server-standalone-2.35.0.jar" &
        - sleep 5
# befor_script:
        # - "sh -e /etc/init.d/xvfb start"
        # - "export DISPLAY=:99.0"
        # - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
        # - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
        # - sleep 5
script: 
        - bin/behat Tests/Goutte/test.feature
#        - vendor/bin/phpunit
email:
    recipients:
      - anthonydeniaud@gmail.com
    #on_success: always #doc: http://about.travis-ci.org/docs/user/notifications/
