language: php

php:
    - 5.3
    - 5.4

#before_script:
#    - git clone --depth 1 git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp
#    - mv ../CakePHP-Upload 

before_script: php vendor/vendors.php
script: php vendor/phpunit/phpunit/phpunit.php