language: php

php:
    - 5.3
    - 5.4

#before_script:
#    - git clone --depth 1 git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp
#    - mv ../CakePHP-Upload 

script:
    - $ vendor/phpunit/phpunit/phpunit.php