language: php
php:
    - 5.4
before_install:
        - sudo apt-get update
        - sudo apt-get install apache2
        - sudo apt-get install libapache2-mod-php5
        - sudo apt-get install firefox
#        - firefox -v
#        - composer install --dev --prefer-source
        - chmod +x bin/behat
        - sudo chmod 777 /var/www
        - cp -r /home/travis/build/TWAD/tests /var/www/TEST
        - cd /var/www/TEST
        - wget https://selenium.googlecode.com/files/selenium-server-standalone-2.35.0.jar
        - java -jar "selenium-server-standalone-2.35.0.jar" &
script: 
        - bin/behat Tests/Goutte/test.feature
#        - vendor/bin/phpunit
email:
    recipients:
      - anthonydeniaud@gmail.com
    #on_success: always #doc: http://about.travis-ci.org/docs/user/notifications/
