language: php
php:
    - 5.3
    - 5.4
before_script: composer install --dev --prefer-source
script: vendor/bin/phpunit

notifications:
  email:
  recipients:
  -anthonydeniaud@gmail.com
    on_success: always
    on_failure: always